name: Test Blackjack

on:
    workflow_dispatch:
    push:
        branches: main
    pull_request:
        branches: main

jobs:
    speak:
        runs-on: ubuntu-latest
        steps:
            - name: speak
              run: echo Testing Blackjack!
        

    test:
        runs-on: ubuntu-latest
        strategy:
            matrix:
                python-version: ["3.12"]
        steps:
            - name: Checkout repository
              uses: actions/checkout@v4
              
            - name: Test Blackjack 
              run: |
                python -m pip install --upgrade pip
                pip install pytest
                pytest